DIETARY_RESTRICTIONS = {
    "Intolerância à Lactose": {
        "description": "Dificuldade em digerir a lactose, açúcar presente no leite",
        "common_ingredients": ["leite", "queijo", "iogurte", "creme de leite"],
        "meal_suggestions": {
            "cafe_da_manha": [
                "Mingau de aveia com leite de amêndoas e banana",
                "Pão integral com pasta de abacate e ovo mexido",
                "Smoothie de frutas com leite de coco",
                "Tapioca com frango desfiado e tomate",
                "Panqueca de banana com mel",
                "Torrada com geleia e frutas frescas",
                "Granola sem lactose com frutas secas",
                "Bolo de cenoura sem lactose",
                "Crepioca com queijo sem lactose",
                "Vitamina de frutas com leite de arroz",
                "Pão de queijo sem lactose",
                "Cuscuz com ovos mexidos",
                "Waffles sem lactose com mel",
                "Muffin de banana sem lactose",
                "Salada de frutas com granola",
                "Torrada com homus",
                "Wrap de vegetais com ovo",
                "Pancake de aveia sem lactose",
                "Iogurte de coco com frutas",
                "Mingau de quinoa com leite vegetal",
                "Pão integral com pasta de amendoim",
                "Bowl de açaí com granola sem lactose",
                "Omelete de legumes",
                "Tapioca com coco e banana",
                "Smoothie bowl com frutas frescas"
            ],
            "almoco": [
                "Arroz integral com frango grelhado e legumes",
                "Salada de quinoa com grão de bico e vegetais",
                "Macarrão sem glúten ao molho de tomate",
                "Peixe assado com batatas e brócolis",
                "Strogonoff de frango com leite de coco",
                "Bowl de proteína com arroz e legumes",
                "Hambúrguer caseiro com salada",
                "Wrap de frango com legumes",
                "Yakisoba de legumes com frango",
                "Risoto de cogumelos com leite de arroz",
                "Escondidinho de mandioca com carne",
                "Bife grelhado com purê sem lactose",
                "Salada caesar sem queijo",
                "Feijoada vegetariana",
                "Penne ao molho rose sem lactose",
                "Filé de peixe com legumes assados",
                "Bowl de feijão preto com arroz",
                "Frango assado com batatas",
                "Carne moída com legumes",
                "Quibe assado com salada",
                "Lasanha com molho branco sem lactose",
                "Moqueca de peixe com leite de coco",
                "Picadinho com arroz integral",
                "Legumes assados com quinoa",
                "Macarrão integral ao pesto sem queijo"
            ],
            "jantar": [
                "Sopa de legumes com frango",
                "Omelete com vegetais e batata doce",
                "Salada de atum com folhas verdes",
                "Bowl de proteína com quinoa",
                "Wraps de alface com frango",
                "Canja de galinha",
                "Salmão grelhado com aspargos",
                "Hambúrguer de grão de bico",
                "Sopinha de abóbora",
                "Peito de frango com purê sem lactose",
                "Salada de grãos com atum",
                "Panqueca de aveia com frango",
                "Bowl de legumes assados",
                "Tofu grelhado com legumes",
                "Caldo verde sem leite",
                "Ovos pochê com torrada integral",
                "Sopa de feijão com legumes",
                "Peixe cozido com batatas",
                "Mix de folhas com frango desfiado",
                "Wrap de atum com vegetais",
                "Yakisoba de legumes",
                "Quinoa com legumes e tofu",
                "Sopa de lentilhas",
                "Omelete de forno com legumes",
                "Bowl de proteína com vegetais"
            ]
        },
    },
    "Alergia à Proteína do Leite": {
        "description": "Reação imunológica às proteínas presentes no leite",
        "common_ingredients": ["caseína", "whey protein", "lactoalbumina", "lactoglobulina"],
        "meal_suggestions": {
            "cafe_da_manha": [
                "Mingau de aveia com leite de amêndoas e banana",
                "Pão integral com pasta de abacate e ovo",
                "Smoothie de frutas com leite de coco",
                "Tapioca com frango desfiado e tomate",
                "Panquecas de banana com xarope de bordo",
                "Torradas com pasta de amendoim e geleia",
                "Granola caseira com frutas secas e leite de arroz",
                "Bolo de cenoura vegano",
                "Crepioca com cogumelos",
                "Vitamina de frutas com leite de amêndoas",
                "Pão de batata doce",
                "Cuscuz com ovos mexidos",
                "Waffles de banana com mel",
                "Muffin de maçã vegano",
                "Salada de frutas com granola caseira",
                "Torrada com homus e tomate",
                "Wrap de vegetais com ovo",
                "Mingau de chia com leite de coco",
                "Iogurte de coco com frutas vermelhas",
                "Bowl de açaí puro com granola",
                "Pão integral com abacate e sementes",
                "Panquecas de aveia com frutas",
                "Omelete de legumes",
                "Tapioca com coco e banana",
                "Smoothie bowl de manga e maracujá"
            ],
            "almoco": [
                "Arroz integral com frango grelhado e legumes",
                "Salada de quinoa com grão de bico",
                "Macarrão sem glúten ao molho de tomate",
                "Peixe assado com batatas e brócolis",
                "Strogonoff de frango com leite de coco",
                "Arroz com feijão e bife grelhado",
                "Hambúrguer caseiro com salada",
                "Wrap de frango com legumes",
                "Yakisoba de legumes com frango",
                "Risoto de cogumelos com leite de coco",
                "Escondidinho de mandioca com carne",
                "Filé de frango com purê de batata",
                "Salada de grãos com atum",
                "Feijoada vegana",
                "Penne ao molho de tomate fresco",
                "Salmão grelhado com legumes",
                "Bowl de feijão preto com arroz",
                "Frango assado com batatas",
                "Carne moída com legumes",
                "Quibe assado com salada",
                "Lasanha com molho de tomate",
                "Moqueca de peixe com leite de coco",
                "Picadinho com arroz integral",
                "Legumes assados com quinoa",
                "Macarrão integral ao molho pesto vegano"
            ],
            "jantar": [
                "Sopa de legumes com frango",
                "Omelete com vegetais",
                "Salada de atum com folhas verdes",
                "Bowl de quinoa com legumes grelhados",
                "Wraps de alface com frango",
                "Canja de galinha",
                "Salmão grelhado com aspargos",
                "Hambúrguer de grão de bico",
                "Sopa de abóbora com leite de coco",
                "Peito de frango com purê de mandioca",
                "Salada de grãos com atum",
                "Panqueca de aveia com frango",
                "Bowl de legumes assados",
                "Tofu grelhado com legumes",
                "Caldo verde com leite de coco",
                "Ovos pochê com torrada integral",
                "Sopa de feijão com legumes",
                "Peixe cozido com batatas",
                "Mix de folhas com frango desfiado",
                "Wrap de atum com vegetais",
                "Yakisoba vegano",
                "Quinoa com legumes e tofu",
                "Sopa de lentilhas",
                "Omelete de forno com legumes",
                "Bowl de grãos com vegetais grelhados"
            ]
        }
    },
    "Sensibilidade ao Glúten": {
        "description": "Sensibilidade não-celíaca ao glúten",
        "common_ingredients": ["trigo", "centeio", "cevada", "malte"],
        "meal_suggestions": {
            "cafe_da_manha": [
                "Tapioca recheada com ovos e espinafre",
                "Mingau de quinoa com frutas vermelhas",
                "Pão de mandioca com pasta de abacate",
                "Panquecas de banana e aveia sem glúten",
                "Bowl de açaí com granola sem glúten",
                "Crepioca com queijo e tomate",
                "Omelete de legumes com batata doce",
                "Vitamina de frutas com chia",
                "Bolo de milho sem glúten",
                "Cuscuz de milho com ovos mexidos",
                "Smoothie bowl com frutas e sementes",
                "Pão de queijo",
                "Iogurte com frutas e sementes de abóbora",
                "Panqueca de arroz com mel",
                "Muffin de banana sem glúten",
                "Wrap de alface com atum",
                "Mingau de amaranto com canela",
                "Salada de frutas com granola sem glúten",
                "Waffle de batata doce",
                "Toast de pão sem glúten com abacate",
                "Bowl de iogurte com frutas secas",
                "Bolo de cenoura sem glúten",
                "Chips de banana com pasta de amendoim",
                "Torta salgada de quinoa",
                "Pudim de chia com leite de coco"
            ],
            "almoco": [
                "Arroz com feijão e bife grelhado",
                "Salmão grelhado com purê de batatas",
                "Frango assado com legumes",
                "Risoto de quinoa com cogumelos",
                "Macarrão de arroz com molho bolonhesa",
                "Feijoada com farofa de mandioca",
                "Bowl de atum com arroz e abacate",
                "Strogonoff com arroz integral",
                "Yakisoba com macarrão de arroz",
                "Moqueca de peixe com pirão",
                "Escondidinho de mandioca",
                "Bobó de camarão",
                "Salada de quinoa com frango",
                "Filé de peixe com batatas rústicas",
                "Hambúrguer com pão sem glúten",
                "Abobrinha recheada com carne moída",
                "Polenta cremosa com ragu",
                "Bowl de açaí salgado com camarão",
                "Curry de frango com arroz",
                "Picadinho com purê de mandioquinha",
                "Lasanha de berinjela",
                "Nhoque de batata doce",
                "Cubos de frango com legumes",
                "Parmegiana com farinha sem glúten",
                "Filé de peixe à milanesa sem glúten"
            ],
            "jantar": [
                "Sopa de legumes com quinoa",
                "Omelete com batatas e ervas",
                "Arroz de couve-flor com frango",
                "Bolinho de arroz com atum",
                "Purê de mandioca com carne moída",
                "Wrap de alface com frango",
                "Sopa de abóbora com gengibre",
                "Bowl de poke sem molho shoyu",
                "Quibe de quinoa assado",
                "Salada de batata com atum",
                "Berinjela recheada com carne",
                "Chips de mandioca com guacamole",
                "Caldo verde sem pão",
                "Frango grelhado com legumes",
                "Tofu grelhado com arroz",
                "Moqueca de palmito",
                "Atum selado com purê de cenoura",
                "Sopinha de mandioquinha",
                "Ovos pochê com espinafre",
                "Salada de grãos sem glúten",
                "Escondidinho de batata doce",
                "Legumes assados com ervas",
                "Carne moída com abobrinha",
                "Panqueca de arroz com frango",
                "Bowl de legumes com quinoa"
            ]
        }
    },
    "Alergia a Frutos do Mar": {
        "description": "Reação alérgica a frutos do mar",
        "common_ingredients": ["camarão", "lagosta", "caranguejo", "mariscos"],
        "meal_suggestions": {
            "cafe_da_manha": [
                "Pão integral com ovos mexidos",
                "Mingau de aveia com frutas",
                "Tapioca com queijo e tomate",
                "Vitamina de banana com aveia",
                "Panquecas de banana com mel",
                "Iogurte com granola e frutas frescas",
                "Omelete de queijo com espinafre",
                "Smoothie de frutas vermelhas",
                "Bolo de cenoura caseiro",
                "Pão de queijo",
                "Crepioca com frango desfiado",
                "Torradas com pasta de amendoim",
                "Bowl de açaí com granola",
                "Cuscuz com ovos",
                "Waffle integral com mel",
                "Muffin de maçã com canela",
                "Sanduíche natural de frango",
                "Mingau de quinoa com leite",
                "Panqueca de aveia com banana",
                "Toast de abacate com ovo pochê",
                "Wrap de peito de peru",
                "Bolo de milho",
                "Salada de frutas com iogurte",
                "Pão integral com ricota e mel",
                "Vitamina de mamão com aveia"
            ],
            "almoco": [
                "Arroz com feijão e bife grelhado",
                "Frango assado com batatas",
                "Macarrão à bolonhesa",
                "Estrogonofe de frango",
                "Feijoada tradicional",
                "Lasanha de carne moída",
                "Arroz integral com frango grelhado",
                "Escondidinho de carne seca",
                "Nhoque ao molho de tomate",
                "File de frango à parmegiana",
                "Picadinho de carne com legumes",
                "Penne ao molho rosé",
                "Hambúrguer caseiro com salada",
                "Carne assada com purê",
                "Galinhada com milho e ervilhas",
                "Yakisoba de frango",
                "Arroz de forno com frango",
                "Bife a rolê com legumes",
                "Macarrão carbonara",
                "Carne moída com polenta",
                "Risoto de frango com funghi",
                "Strogonoff de carne",
                "Espaguete com almôndegas",
                "Frango xadrez com arroz",
                "File de porco grelhado com legumes"
            ],
            "jantar": [
                "Sopa de legumes com frango",
                "Omelete com queijo e tomate",
                "Salada Caesar com frango",
                "Sanduíche de frango grelhado",
                "Canja de galinha",
                "Wrap de peito de peru com queijo",
                "Macarrão com molho branco",
                "Torta de frango",
                "Crepioca com queijo e presunto",
                "Cuscuz paulista",
                "Salada de grãos com frango",
                "Panqueca de carne moída",
                "Bowl de quinoa com frango",
                "Sopa de feijão com legumes",
                "Ovos mexidos com pão integral",
                "Quiche de legumes",
                "Arroz integral com legumes",
                "Salada de batatas com frango",
                "Misto quente com salada",
                "Sopa de abóbora",
                "Tapioca com frango e queijo",
                "Legumes assados com frango",
                "Pizza caseira de frango",
                "Bowl de proteínas vegetais",
                "Rocambole de carne moída"
            ]
        }
        },
        "Alergia a Amendoim": {
            "description": "Reação alérgica ao amendoim e derivados",
            "common_ingredients": ["amendoim", "pasta de amendoim", "óleo de amendoim"],
            "meal_suggestions": {
                "cafe_da_manha": [
                    "Pão integral com queijo e tomate",
                    "Mingau de aveia com banana e mel",
                    "Iogurte com granola sem amendoim",
                    "Tapioca com queijo e oregano",
                    "Omelete com espinafre",
                    "Smoothie de frutas vermelhas com chia",
                    "Bolo de cenoura caseiro",
                    "Torradas com geleia e ricota",
                    "Crepioca com frango e queijo",
                    "Vitamina de morango com aveia",
                    "Pão de queijo",
                    "Panqueca de banana com mel",
                    "Sanduíche natural de peito de peru",
                    "Bowl de açaí com frutas frescas",
                    "Cuscuz com ovos mexidos",
                    "Wrap de presunto e queijo",
                    "Muffin de maçã caseiro",
                    "Salada de frutas com iogurte",
                    "Waffle com mel e canela",
                    "Toast de abacate com ovo",
                    "Mingau de quinoa com leite e frutas",
                    "Pão francês com manteiga",
                    "Vitamina de mamão com aveia",
                    "Bolo de laranja caseiro",
                    "Queijo quente com orégano"
                ],
                "almoco": [
                    "Arroz com feijão e bife grelhado",
                    "Frango assado com batatas",
                    "Macarrão à bolonhesa",
                    "Salada de grãos com legumes",
                    "Estrogonofe de frango",
                    "Peixe grelhado com purê",
                    "Lasanha de carne moída",
                    "Arroz integral com legumes",
                    "Escondidinho de carne",
                    "File de frango à milanesa",
                    "Carne assada com legumes",
                    "Risoto de cogumelos",
                    "Nhoque ao sugo",
                    "Hambúrguer caseiro com salada",
                    "Picadinho de carne com arroz",
                    "Yakisoba de frango",
                    "Penne ao molho branco",
                    "Filé de peixe com batatas",
                    "Feijoada tradicional",
                    "Macarrão primavera",
                    "Frango grelhado com quinoa",
                    "Bife a cavalo com arroz",
                    "Galinhada com legumes",
                    "Carne moída com polenta",
                    "Strogonoff com arroz"
                ],
                "jantar": [
                    "Sopa de legumes",
                    "Omelete com queijo e tomate",
                    "Salada Caesar",
                    "Sanduíche de frango light",
                    "Canja de galinha",
                    "Wrap de atum com salada",
                    "Macarrão com molho de tomate",
                    "Torta de frango",
                    "Crepioca com queijo",
                    "Sopa de feijão",
                    "Salada de atum com grãos",
                    "Panqueca de carne moída",
                    "Bowl de quinoa com frango",
                    "Legumes assados com peito de peru",
                    "Ovos mexidos com pão integral",
                    "Quiche de legumes",
                    "Arroz integral com brócolis",
                    "Sopa de abóbora",
                    "Misto quente com salada",
                    "Tapioca com queijo e tomate",
                    "Peixe assado com legumes",
                    "Pizza caseira margherita",
                    "Caldo verde",
                    "Omelete de forno com legumes",
                    "Sopinha de legumes com frango"
                ]
            }
        },
        "Diabetes": {
            "description": "Condição que afeta o metabolismo da glicose",
            "common_ingredients": ["açúcar", "mel", "xarope de milho"],
            "meal_suggestions": {
                "cafe_da_manha": [
                    "Omelete de claras com espinafre",
                    "Iogurte natural sem açúcar com chia",
                    "Pão integral com queijo branco e tomate",
                    "Tapioca com queijo cottage",
                    "Mingau de aveia sem açúcar com canela",
                    "Bowl de iogurte com morangos frescos",
                    "Ovos mexidos com pão integral",
                    "Crepioca com queijo e orégano",
                    "Smoothie verde com couve e limão",
                    "Panqueca integral de banana sem açúcar",
                    "Torradas integrais com ricota e orégano",
                    "Vitamina de morango sem açúcar com aveia",
                    "Sanduíche integral de peito de peru",
                    "Mamão com iogurte natural e linhaça",
                    "Omelete de queijo com tomate",
                    "Cuscuz integral com ovos",
                    "Wrap integral com peito de peru",
                    "Queijo branco com tomate e orégano",
                    "Mingau de quinoa sem açúcar",
                    "Toast de abacate com ovo pochê",
                    "Salada de frutas com iogurte natural",
                    "Pão de queijo fit",
                    "Creme de chia com leite de amêndoas",
                    "Panqueca proteica sem açúcar",
                    "Bowl de cottage com pepino e tomate"
                ],
                "almoco": [
                    "Frango grelhado com legumes no vapor",
                    "Salada de quinoa com frango",
                    "Peixe assado com brócolis",
                    "Omelete de forno com legumes",
                    "Carne grelhada com abobrinha",
                    "Bowl de proteínas com folhas verdes",
                    "Salmão grelhado com aspargos",
                    "Frango assado com legumes",
                    "Carne moída com couve-flor",
                    "Filé de peixe com purê de couve-flor",
                    "Peito de frango com berinjela",
                    "Bife grelhado com salada verde",
                    "Atum com mix de folhas",
                    "Escondidinho de couve-flor",
                    "Hambúrguer caseiro com salada",
                    "Strogonoff fit com palmito",
                    "Peixe grelhado com legumes assados",
                    "Frango com legumes no forno",
                    "Carne assada com abobrinha",
                    "Bowl de atum com quinoa",
                    "Ovos cozidos com salada",
                    "Picadinho com legumes",
                    "Lombo assado com legumes",
                    "Frango xadrez sem amido",
                    "Peixe cozido com vegetais"
                ],
                "jantar": [
                    "Sopa de legumes com frango",
                    "Omelete com espinafre e queijo",
                    "Salada de folhas com atum",
                    "Bowl de cottage com pepino",
                    "Carne moída com couve refogada",
                    "Wrap de alface com frango",
                    "Sopa de abóbora sem creme",
                    "Ovos pochê com espinafre",
                    "Peixe grelhado com abobrinha",
                    "Berinjela recheada com carne",
                    "Salada de atum com folhas",
                    "Frango desfiado com legumes",
                    "Caldo verde sem batata",
                    "Tofu grelhado com vegetais",
                    "Sopa de legumes com carne",
                    "Omelete de forno com queijo",
                    "Bowl de proteína com vegetais",
                    "Abobrinha recheada com frango",
                    "Carne moída com brócolis",
                    "Salada de grãos com frango",
                    "Sopa de couve-flor",
                    "Peixe cozido com legumes",
                    "Torta de legumes sem massa",
                    "Hambúrguer de frango com salada",
                    "Atum com mix de vegetais"
                ]
            }
        },
        "Veganismo": {
            "description": "Dieta sem produtos de origem animal",
            "common_ingredients": ["carne", "leite", "ovos", "mel"],
            "meal_suggestions": {
                "cafe_da_manha": [
                    "Mingau de aveia com leite de amêndoas e banana",
                    "Toast de abacate com tomate e chia",
                    "Smoothie de frutas vermelhas com leite de coco",
                    "Panquecas de banana com calda de frutas",
                    "Tapioca com pasta de amendoim e banana",
                    "Bowl de açaí com granola vegana",
                    "Pão integral vegano com homus",
                    "Vitamina de mamão com leite de aveia",
                    "Overnight oats com leite de soja e frutas",
                    "Bolo vegano de cenoura",
                    "Mingau de quinoa com leite vegetal",
                    "Crepioca vegana com tofu temperado",
                    "Waffle vegano com frutas frescas",
                    "Torradas com pasta de abacate",
                    "Smoothie bowl de manga com granola",
                    "Iogurte de coco com frutas",
                    "Pão vegano com guacamole",
                    "Cuscuz com legumes",
                    "Bowl de chia com leite de amêndoas",
                    "Panquecas de aveia com frutas",
                    "Wrap vegano com homus e vegetais",
                    "Batida verde com espinafre e banana",
                    "Granola caseira com leite vegetal",
                    "Muffin vegano de banana",
                    "Fatias de abacate com tomate cereja"
                ],
                "almoco": [
                    "Curry de grão de bico com arroz integral",
                    "Estrogonofe de cogumelos com arroz",
                    "Feijoada vegana com farofa",
                    "Bowl de quinoa com legumes assados",
                    "Macarrão integral com molho de tomate",
                    "Hambúrguer de lentilha com salada",
                    "Risoto de cogumelos",
                    "Yakisoba vegano de legumes",
                    "Moqueca de palmito com arroz",
                    "Escondidinho de mandioca com proteína de soja",
                    "Lasanha de berinjela",
                    "Salada de grãos com tofu grelhado",
                    "Bobó de palmito",
                    "Nhoque de batata doce ao sugo",
                    "Chili vegano com arroz",
                    "Bowl de feijão preto com abacate",
                    "Strogonoff de palmito",
                    "Abobrinha recheada com quinoa",
                    "Curry de legumes com leite de coco",
                    "Quibe de lentilha assado",
                    "Macarrão com almôndegas de grão de bico",
                    "Torta de legumes vegana",
                    "Falafel com salada",
                    "Legumes assados com tofu",
                    "Arroz com lentilha e legumes"
                ],
                "jantar": [
                    "Sopa de legumes com quinoa",
                    "Wrap de alface com homus",
                    "Bowl de tofu com legumes",
                    "Salada de grãos com abacate",
                    "Creme de abóbora com leite de coco",
                    "Sanduíche vegano de grão de bico",
                    "Yakisoba de legumes",
                    "Cuscuz com legumes grelhados",
                    "Tapioca com cogumelos",
                    "Sopa de feijão com legumes",
                    "Bowl de quinoa com vegetais",
                    "Berinjela recheada com quinoa",
                    "Caldo verde vegano",
                    "Tofu grelhado com vegetais",
                    "Bolinho de grão de bico assado",
                    "Salada de lentilha com vegetais",
                    "Purê de mandioquinha com cogumelos",
                    "Sopa de ervilha",
                    "Panqueca de legumes vegana",
                    "Bowl de vegetais assados",
                    "Quiche sem ovo de legumes",
                    "Arroz integral com grão de bico",
                    "Sopa de tomate com manjericão",
                    "Wrap de grão de bico com vegetais",
                    "Mix de cogumelos com quinoa"
                ]
            }
        },
    }
